### PR TITLE
Darin Pope contributor spotlight

### PR DESCRIPTION
**Pull request by alyssat**
Please do not merge this PR before July 30.

### CODE REVIEW

**Review by krisstern — APPROVED** [review]
LGTM! Thanks @alyssat

**Review by gounthar — APPROVED** [review]
Well done, thanks! 🚀

**Comment by krisstern** [comment]
Looking forward to seeing this PR gets merged @alyssat later today!

**Comment by MarkEWaite** [comment]
Is some other change needed in order to make this contributor spotlight visible?  When I open https://contributors.jenkins.io/ I see that the spotlight of Markus Winter is on the root page and that Darin Pope is not listed anywhere on the page.

**Comment by krisstern** [comment]
I think we may need to contact the Infra team regarding this deployment

**Comment by MarkEWaite** [comment]
Thanks @krisstern .  I've opened:

* https://github.com/jenkins-infra/helpdesk/issues/4207

**Comment by hervelemeur** [comment]
Nodejs install failed, a build restart should be enough. @MarkEWaite can you trigger a new build?

**Comment by dduportal** [comment]
> Nodejs install failed, a build restart should be enough. @MarkEWaite can you trigger a new build?

Thanks. New build has been triggered: https://github.com/jenkins-infra/helpdesk/issues/4207#issuecomment-2260191992
Note that https://github.com/jenkins-infra/contributor-spotlight/pull/169#pullrequestreview-2209789467 was also merged, we'll see the results

**Comment by dduportal** [comment]
Last build was successful and deployed the website (ref. https://github.com/jenkins-infra/helpdesk/issues/4207#issuecomment-2260239215).

**Pull request merged**
