### PR TITLE
feat: add default font-size in body HTML element

### PR DESCRIPTION
**Pull request by krisstern**
Fixes https://github.com/jenkins-infra/jenkins.io/issues/6917

To align the fontsize of `contributor-spotlight` navbar with the rest of the jenkins.io sites by setting the default fontsize in the `body` HTML element to `16px`.

### CODE REVIEW

**Review by sridamul — APPROVED** [review]
LGTM

**Comment by krisstern** [comment]
@kmartens27 This PR also changes the fontsize of the text in the landing page and the contributor details pages. I hope that this is okay with you.

**Comment by krisstern** [comment]
Also @kmartens27 this may be somewhat related to https://github.com/jenkins-infra/jenkins-io-components/pull/116 which is under review.

**Comment by krisstern** [comment]
@lemeurherve You may want to give this PR a review, as I noticed this change may not be enough though.

**Review by kmartens27 — APPROVED** [review]
Thanks for the change here @krisstern, it looks good and aligns with the font on jenkins.io

**Pull request merged**
