### PR TITLE
Daniel krämer contributor spotlight

### PR DESCRIPTION
**Pull request by alyssat**
To be merged on Tuesday, August 27

### CODE REVIEW

**Review by gounthar — APPROVED** [review]
Thanks!

**Review by krisstern — DISMISSED** [review]
LGTM

**Comment by kmartens27** [comment]
The content looks good, thanks very much @alyssat! The only thing that I'm having an issue with is that when I go to the preview, it doesn't load Daniel's picture. I think the special character in the filename is throwing it off. Would it be possible to use an "a" without the umlaut in the image filename and match `:page-image: avatar/daniel-krämer.jpeg`?

**Comment by alyssat** [comment]
> The content looks good, thanks very much @alyssat! The only thing that I'm having an issue with is that when I go to the preview, it doesn't load Daniel's picture. I think the special character in the filename is throwing it off. Would it be possible to use an "a" without the umlaut in the image filename and match `:page-image: avatar/daniel-krämer.jpeg`?

@kmartens27 thanks! The image file name has been edited. Hope that worked.

**Comment by alyssat** [comment]
Removed the character above the 'a' in the file name for the avatar image.

**Comment by kmartens27** [comment]
thanks very much @alyssat, I can confirm the image now appears in the deploy preview
Screenshot 2024-08-26 at 2 38 19 PM
Screenshot 2024-08-26 at 2 38 23 PM

**Review by kmartens27 — APPROVED** [review]
Everything looks great here, thanks again @alyssat!

**Comment by krisstern** [comment]
All set to be merged today! 🚀

**Pull request merged**
