### PR TITLE
Feat: Add responsiveness for tablet and mobile

### LINKED ISSUE #29: Mobile view for contributors site not scaling properly
### What feature do you want to see added?

As pointed out in the [advocacy & outreach gitter channel](https://matrix.to/#/!cRulYWcErlSqXzBIyw:gitter.im/$I82WyoVWlFy2Q4el_UpSeVswSwS7EDhV4BrrWPi4WYE?via=gitter.im&via=matrix.org&via=g4v.dev), the mobile formatting of the contributor spotlight site could be improved. The feature box for the contributor seems to go off the page, and in the contributor page the text sticks to the center of the page.

IMG_5846
IMG_5847

Would it be possible to update the mobile formatting so that the presentation is closer to the regular jenkins.io site?

### Upstream changes

_No response_

### PR DESCRIPTION
**Pull request by krisstern**
Fixes #29. 

Added responsiveness for both tablet and mobile views.

### CODE REVIEW

**Comment by krisstern** [comment]
@kmartens27 I have updated the code to fix the mobile view of the homepage as well as contributor details page.

**Review by kmartens27 — APPROVED** [review]
Testing the site with mobile view looks good! The featured contributor box is no longer off the page and the text is aligned in a readable way.

Thanks very much @krisstern

**Comment by krisstern** [comment]
You are welcome @kmartens27! Glad you like the improved version

**Comment by hervelemeur** [comment]
Looks good, 👍

Maybe reduce the padding inside the homepage card?

Screenshot_20231129-160317

**Comment by kmartens27** [comment]
the updated display looks good!

**Pull request merged**
