### PR TITLE
feat: update deprecated husky command

### PR DESCRIPTION
**Pull request by krisstern**
Updated deprecated `husky install` command to `husky` as per https://github.com/code100x/cms/issues/630.

### CODE REVIEW

**Comment by krisstern** [comment]
@kmartens27 Would it be possible for you to give this a review?

**Review by kmartens27 — APPROVED** [review]
site loads and navigation works as expected, thanks very much @krisstern

**Review by alyssat — COMMENTED** [review]
LGTM. Thank you @krisstern for your work on this

**Comment by krisstern** [comment]
You are welcome @alyssat!

**Pull request merged**
