### PR TITLE
feat: fine-tune CSS styling for images of different dimensions

### PR DESCRIPTION
**Pull request by krisstern**
1. Enhanced the look and feel of for avatar images of different shapes and sizes.
2. Enhanced the look and feel for responsiveness especially for the mobile view. 
3. Tried to center texts as much as possible.

### CODE REVIEW

**Comment by krisstern** [comment]
@kmartens27 I have checked out the pull request for the soon-to-be-released PR #7 and think maybe a bit of tweaking of our CSS will enhance the look and feel a bit, for example to ensure that the avatar images of all contributors are rounded. Please check this out and let me know if any other changes are necessary. Cheers!

**Review by kmartens27 — CHANGES_REQUESTED** [review]
I like the updates to text & styling, and my other comment has related feedback on images.

Thanks very much @krisstern

**Comment by krisstern** [comment]
Strange, I thought I fixed the size of the round images already in this RP. Let me check again...

**Comment by krisstern** [comment]
> Thanks very much @krisstern!
> 
> When checking out the deploy, it appears that the image frame for non-featured contributors scales and depending on the mobile screen size, may or may not show the whole image. Screenshot 2023-11-30 at 10 07 14 AM Screenshot 2023-11-30 at 10 07 34 AM
> 
> Additionally, it looks as though the contributor page stretches the image if the page is full screen Screenshot 2023-11-30 at 10 07 43 AM
> 
> Would it be possible to have a set size limit and have the image & frame scale as a single item?

Yeah, these are exactly what this PR is for fixing.

**Review by kmartens27 — APPROVED** [review]
Thanks for clarifying @krisstern!!

**Comment by krisstern** [comment]
This is what we get after this PR on the contributor details page:

Screenshot 2023-11-30 at 11 42 14 PM

**Pull request merged**
