### PR TITLE
March 25 2024 - adding Bruno Verachten Contributor Spotlight

### PR DESCRIPTION
**Pull request by kmartens27**
This PR is for the contributor spotlight page of @gounthar 

I have resized and compressed the avatar image so that should be adequate/appropriate for use. I have also updated some of the links and adjusted the original grammar.

### CODE REVIEW

**Comment by kmartens27** [comment]
@gounthar when you have some time, would you be able to review?

**Comment by kmartens27** [comment]
link to preview of spotlight page for Bruno: https://deploy-preview-105--contributor-spotlight.netlify.app/pages/contributors/bruno-verachten/

**Review by MargoBGH — APPROVED** [review]
Looks great!

**Review by gounthar — APPROVED** [review]
Thanks;, Kevin!

**Review by krisstern — APPROVED** [review]
LGTM

**Pull request merged**
