### PR TITLE
Olivier lamy spotlight

### PR DESCRIPTION
**Pull request by kmartens27**
This is to resubmit the PR for re-adding Olivier Lamy's spotlight, as I deleted my previous repository. In doing so, I forgot that everything attached to it would be deleted and removed. The [previous PR](https://github.com/jenkins-infra/contributor-spotlight/pull/187) was reviewed and approved, and no content has changed.

This is scheduled to be published today.

### CODE REVIEW

**Review by gounthar — APPROVED** [review]
Thanks, Kevin!

**Comment by krisstern** [comment]
Some tests are still failing, or I could approve it for you @kmartens27

**Comment by krisstern** [comment]
Looks like the test failures are due to:
```shell
Deploy PR to preview site / Shell Script
Error in sh step, with arguments netlify-deploy --draft=true --siteName "contributor-spotlight" --title "Preview deploy for ${CHANGE_ID}" --alias "deploy-preview-${CHANGE_ID}" -d ./public.
```

Let me follow up with a ticket with helpdesk.

**Comment by krisstern** [comment]
Infra helpdesk ticket created here: https://github.com/jenkins-infra/helpdesk/issues/4284

**Review by krisstern — APPROVED** [review]
LGTM

**Comment by dduportal** [comment]
@jenkins-infra/contributor-spotlight 

As per https://github.com/jenkins-infra/helpdesk/issues/4284: you can safely force-merge the PR if only the infra.ci checks are failing (but the other checks - ci.jenkins.io- are passing)

**Comment by krisstern** [comment]
Hi @dduportal I have checked but cannot find a force-merge option for the @jenkins-infra/contributor-spotlight team, is there anything else we can do to enabled merging without the required `pr-merge` check passing first?

**Comment by dduportal** [comment]
> Hi @dduportal I have checked but cannot find a force-merge option for the @jenkins-infra/contributor-spotlight team, is there anything else we can do to enabled merging without the required `pr-merge` check passing first?

I just added a few permissions : can you re-check please?

**Comment by krisstern** [comment]
Nope @dduportal still the same for me:

Screenshot 2024-09-10 at 11 03 31 PM

**Comment by dduportal** [comment]
@krisstern thanks! I've removed the branch protection for the failing check: you should be allowed to merge without requiring the "force"

**Comment by krisstern** [comment]
Thanks @dduportal I think it should work now! I will let @kmartens27 merge this himself later today ET.

**Comment by dduportal** [comment]
For info: the error is related to the permission issue with the token used to deploy. Merging might not deploy.

We're looking into this but not hesitate to merge and comment in https://github.com/jenkins-infra/helpdesk/issues/4284 (the issue opened by Kris) if it fails.

**Comment by dduportal** [comment]
Problem fixed \o/ Preview are back but **only** for maintainers and admins of website repositories

**Comment by krisstern** [comment]
Thanks @dduportal for the follow-up!

**Pull request merged**
