### PR TITLE
feat: add `eslint` and `prettier` and add opengraph metadata

### LINKED ISSUE #43: Fix missing opengraph metadata
### Reproduction steps

N/A

### Expected Results

Each contributor page has opengraph metadata set to ensure the profile picture, summary and background fit nicely independant of the site embedding a post.

### Actual Results

Due to the lack of opengraph metadata, thumbnails are treated differently depending on your browser.

### Anything else?

_No response_

### LINKED ISSUE #54: Set up prettier and eslint for repo
### What feature do you want to see added?

Would like to see `prettier` and `eslint` integrated to this gatsby app using https://www.gatsbyjs.com/plugins/gatsby-plugin-prettier-eslint/. 

### Upstream changes

_No response_

### PR DESCRIPTION
**Pull request by krisstern**
Fixes #43, fixes #54

1. To add `eslint` and `prettier` to the workflow to enable proper formatting of code. This will facilitate code contributions from outside. 
2. To add `opengraph` metadata to contributor details page. Will need to test via preview.

### CODE REVIEW

**Comment by krisstern** [comment]
Looks nice for the homepage og image now:

Screenshot 2023-12-13 at 10 55 41 PM

**Comment by krisstern** [comment]
This is how it looks for the contributor details page og image:

Screenshot 2023-12-13 at 10 56 52 PM

Does this look okay to you @kmartens27?

**Comment by kmartens27** [comment]
I like it, and it looks good from the preview! @alyssat does this work for you for the social posts?

**Comment by krisstern** [comment]
Here is an example of the og metadata we have included for each page:

Screenshot 2023-12-13 at 11 13 51 PM

**Comment by krisstern** [comment]
Added a og:title metadata to have Alex Earl name as the title in opengraph, contract the above where it just says "Contributor Spotlight":

Screenshot 2023-12-13 at 11 15 59 PM

**Comment by kmartens27** [comment]
That is much better, having the contributor name is a better introduction/visual aspect. Thanks so much @krisstern

**Review by kmartens27 — APPROVED** [review]
Thanks very much @krisstern, this looks great!

**Pull request merged**
