### PR TITLE
May 22 2024 - Creating Jan Faracik's spotlight

### PR DESCRIPTION
**Pull request by kmartens27**
This PR is for the contributor spotlight page of Jan Faracik (@janfaracik), and ensures the feature flag is turned to false on the previous spotlight page.

### CODE REVIEW

**Comment by kmartens27** [comment]
@janfaracik would you be able to review when you have a moment? Sorry for the delay in creating the PR, I've been out/away from my computer for a bit, but didn't want to miss publishing your story!

**Comment by alyssat** [comment]
Hi @kmartens27  the first paragraph appears to be cut off when in the Preview (View file).  Other than that the rest looks good to me.

**Review by gounthar — APPROVED** [review]

**Comment by kmartens27** [comment]
Thanks @alyssat and @gounthar!

I've adjusted the intro paragraph so that it is unified instead of broken up. (The view it had presented was how I had formatted it, but since it was only two lines, I just combined everything to one intro and it looks much better.

**Comment by janfaracik** [comment]
> @janfaracik would you be able to review when you have a moment? Sorry for the delay in creating the PR, I've been out/away from my computer for a bit, but didn't want to miss publishing your story!

Looks great - thanks!

**Review by LizGaudet — APPROVED** [review]
lgtm! I just added my own stylistic comments -- feel free to disregard.

**Review by alyssat — APPROVED** [review]
I enjoyed reading the story. Content LGTM.

**Pull request merged**
